on: [push, pull_request]

name: R-CMD-check-docker

jobs:
  R-CMD-check-docker:
    runs-on: ubuntu-latest
    
    name: ${{ matrix.config.image }}-${{ matrix.config.gcc}}

    strategy:
      fail-fast: false
      matrix:
        config:
        - {image: "sckott/fedora-clang-devel-spatial", gcc: "10", rscript: "/opt/R-devel/bin/Rscript"}
        
    container: ${{ matrix.config.image }}
    
    steps:
      - uses: actions/checkout@v1
      
      - uses: r-lib/actions/setup-pandoc@master
      
      - name: Set R_LIBS
        run: |
          export R_LIBS="$(${{ matrix.config.rscript }} -e 'cat(.libPaths()[1])')"
          echo "::set-env name=R_LIBS::$R_LIBS"
      
      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS }}
          key: ${{ runner.os }}-${{ matrix.config.image }}-${{ matrix.config.gcc }}-${{ hashFiles('DESCRIPTION') }}
          
      - name: Install dependencies
        run: ${{ matrix.config.rscript }} -e "options(repos=c(CRAN='https://cloud.r-project.org/')); install.packages('remotes')" -e "options(repos=c(CRAN='https://cloud.r-project.org/')); remotes::install_deps(dependencies = TRUE)" -e "remotes::install_cran('rcmdcheck')"

      - name: Check
        run: ${{ matrix.config.rscript }} -e "rcmdcheck::rcmdcheck(args = c('--no-manual', '--as-cran'), error_on = 'warning', check_dir = 'check')"

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-${{ matrix.config.gcc }}
          path: check
